version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - rabbit_container
    command: python3 Flask_currency.py
    environment:
      - RABBIT_HOST = rabbit_container

  rabbit_container:
    image: "rabbitmq:3.8.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbit_container

  celery_beat_container:
    build: .
    command: celery -A celery_work beat -s ./utils/celerybeat-schedule.db
    depends_on:
      - rabbit_container
    environment:
      - RABBIT_HOST=rabbit_container

  celery_worker_container:
    build: .
    command: celery -A celery_work worker --loglevel=INFO --pool=solo
    depends_on:
      - rabbit_container
    environment:
      - RABBIT_HOST=rabbit_container


